require("core.plugins")
require("core.tree")
require("core.bufferline")
require("core.settings")
require("core.autopairs")
require("core.luabar")
require("core.treesitter")
require("core.lsp")
-- require("core.telescope")